"""Precompute the landing page's worked example from the champion model.

The page must show a real ranking within two seconds of loading, without the
visitor typing anything and without a network round trip. So the example is
computed at build time and embedded.

Two rules:
  1. It is computed by the SAME code path the API uses, so what a visitor sees
     first is the real model, not a hand-written illustration.
  2. If there is no champion model, this writes status="untrained" and the page
     renders an honest notice. It never fabricates a ranking to fill the hero.
"""
from __future__ import annotations

import json
import pathlib
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "ml"))

OUT = ROOT / "web" / "src" / "lib" / "generated" / "worked_example.json"

# Real subject lines of the kind the audience writes. Not lorem, not fabricated
# performance data - just three plausible candidates for the model to rank.
EXAMPLE = [
    "Why your best customers leave",
    "The one chart that explains your churn",
    "We looked at 400 churn surveys. Here's what we found.",
]

UNTRAINED = {
    "status": "untrained",
    "note": ("Regenerated by ml/scripts/build_worked_example.py from the champion "
             "model. While status is 'untrained' the page shows an honest notice "
             "instead of a ranking - it never invents numbers to fill the hero."),
    "generatedAt": None,
    "modelVersion": None,
    "comparison": None,
}


def main() -> int:
    # The PROMOTED champion, in the serving directory -- not the training output.
    # This read used to point at ml/artifacts/champion.*, a path nothing in the
    # pipeline ever creates: training writes <model>.onnx there and
    # promote_model.py copies the chosen one to web/model/champion.onnx. So the
    # script always took the "untrained" branch and the landing page kept showing
    # the no-model notice after a successful promotion.
    #
    # Reading the served artifact is also the correct semantics: the worked
    # example must be what the deployed model actually says, not what some other
    # artifact in the training directory would have said.
    serving = ROOT / "web" / "model"
    meta_path = serving / "champion.meta.json"
    onnx_path = serving / "champion.onnx"

    if not (meta_path.exists() and onnx_path.exists()):
        OUT.write_text(json.dumps(UNTRAINED, indent=2) + "\n", encoding="utf-8")
        print("no champion model - wrote status=untrained (the page will say so)")
        return 0

    import numpy as np
    from subjectrank.export_onnx import onnx_prob_fn
    from subjectrank.features import extract, feature_names
    from subjectrank.ranking import rank

    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    names = feature_names()
    keep = [names.index(n) for n in meta["feature_names"]]
    prob = onnx_prob_fn(onnx_path, keep)

    r = rank(prob, EXAMPLE)
    order, scores, P, conf = r["order"], r["scores"], r["pairwise"], r["confidence"]

    lines = []
    for pos, i in enumerate(order):
        vec = extract(EXAMPLE[i])
        lines.append({
            "index": i,
            "text": EXAMPLE[i],
            "rank": pos + 1,
            "score": scores[i],
            "confidence": conf[i],
            "features": {n: v for n, v in zip(names, vec)},
            "pairwise": {str(j): P[i][j] for j in range(len(EXAMPLE)) if j != i},
        })

    too_close = []
    for a in range(len(lines) - 1):
        if abs(lines[a]["score"] - lines[a + 1]["score"]) < 0.04:
            too_close.append([lines[a]["index"], lines[a + 1]["index"]])

    payload = {
        "status": "ready",
        "note": "Computed from the champion model by ml/scripts/build_worked_example.py.",
        "generatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "modelVersion": meta["version"],
        "comparison": {
            "modelVersion": meta["version"],
            "featureSpecVersion": meta["feature_spec_version"],
            "lines": lines,
            "tooCloseToCall": too_close,
            "inferenceMs": 0,
        },
        "meta": meta,
    }
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote worked example from model {meta['version']}: "
          f"winner is {lines[0]['text']!r}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
