#!/usr/bin/env bash
# One script, from an empty subscription to a live URL.
#
#     az login                  # yours to run; this script never sees a credential
#     bash azure/deploy.sh
#
# Idempotent: safe to re-run. It stops at the first failure rather than
# continuing with a half-built environment, and it validates the template before
# creating anything.
#
# It uses `az acr build`, so the image is built INSIDE Azure — no local Docker
# daemon, no `docker login`, no pushing 523 MB over your uplink.
set -euo pipefail

RG="${RG:-subjectrank-rg}"
LOCATION="${LOCATION:-westeurope}"
PREFIX="${PREFIX:-subjectrank}"
PARAMS=azure/infra/main.parameters.json

say()  { printf '\n\033[1m== %s\033[0m\n' "$*"; }
fail() { printf '\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
say "0. Preflight"

command -v az >/dev/null || fail "Azure CLI not found. Install it, then run: az login"
az account show >/dev/null 2>&1 || fail "Not logged in. Run: az login"

SUB_ID=$(az account show --query id -o tsv)
echo "  subscription: $(az account show --query name -o tsv)"
echo "  id:           $SUB_ID"

# Needed by every azure/ml step. Installing it now beats failing later with a
# message that does not mention the extension.
az extension show --name ml >/dev/null 2>&1 || {
  echo "  installing the 'ml' extension..."
  az extension add --name ml --only-show-errors
}

# The Dockerfile refuses to build without the model, but failing here gives a
# better error than failing inside a remote build log.
[ -f web/model/champion.onnx ] || fail \
  "web/model/champion.onnx is missing. Run: python ml/scripts/promote_model.py"
echo "  champion:     $(python -c "import json;print(json.load(open('web/model/champion.meta.json'))['version'])")"

# The real parameters file is gitignored because deploy.sh writes a secret into
# it. A fresh clone therefore has only the example, so seed from it.
[ -f "$PARAMS" ] || {
  cp azure/infra/main.parameters.example.json "$PARAMS"
  echo "  seeded $PARAMS from the example"
}

# The app refuses to start in production without a real SESSION_SECRET, and
# shipping the placeholder would let anyone forge another visitor's session.
if grep -q "REPLACE_ME" "$PARAMS"; then
  SECRET=$(openssl rand -base64 32)
  python - "$PARAMS" "$SECRET" <<'PY'
import json, sys
p, secret = sys.argv[1], sys.argv[2]
d = json.load(open(p))
d["parameters"]["sessionSecret"]["value"] = secret
json.dump(d, open(p, "w"), indent=2)
print("  generated a SESSION_SECRET into", p)
PY
  echo "  NOTE: that file now holds a secret. It is gitignored; keep it that way."
fi

# ---------------------------------------------------------------------------
say "1. Resource group"
az group create -n "$RG" -l "$LOCATION" --only-show-errors -o none
echo "  $RG in $LOCATION"

# ---------------------------------------------------------------------------
say "2a. Validate the template before creating anything"
# This template has not been run against a real subscription. Validating first
# means a template error costs seconds instead of leaving a half-built resource
# group that needs cleaning up before the next attempt.
az deployment group validate \
  -g "$RG" -f azure/infra/main.bicep -p "@$PARAMS" \
  -p deployMachineLearning=false \
  -o none --only-show-errors \
  || fail "template validation failed — nothing was created; fix the error above"
echo "  valid"

# ---------------------------------------------------------------------------
say "2b. App infrastructure"
# The Azure ML workspace is deployed separately in step 6: it is the slowest part
# and the likeliest to fail on a fresh subscription, and the app does not depend
# on it because the model is baked into the image. Getting the site live first
# means an ML quota problem does not cost you the deploy.
echo "  2-4 minutes"
OUT=$(az deployment group create \
  -g "$RG" -f azure/infra/main.bicep -p "@$PARAMS" \
  -p deployMachineLearning=false \
  --query properties.outputs -o json --only-show-errors)

pluck() { echo "$OUT" | python -c "import sys,json;print(json.load(sys.stdin)['$1']['value'])"; }
ACR_NAME=$(pluck acrName)
ACR_SERVER=$(pluck acrLoginServer)
APP_NAME=$(pluck containerAppName)
APP_URL=$(pluck appUrl)
STORAGE=$(pluck storageAccountName)
WORKSPACE="${PREFIX}-ml"

echo "  registry:  $ACR_SERVER"
echo "  app:       $APP_NAME"
echo "  storage:   $STORAGE"

cat > azure/.env.local <<EOF
# Generated by azure/deploy.sh. Gitignored. Source this for the ML steps.
export AZURE_SUBSCRIPTION_ID=$SUB_ID
export AZURE_RESOURCE_GROUP=$RG
export AZURE_ML_WORKSPACE=$WORKSPACE
export ACR_NAME=$ACR_NAME
export CONTAINER_APP=$APP_NAME
export STORAGE_ACCOUNT=$STORAGE
export APP_URL=$APP_URL
EOF
echo "  wrote azure/.env.local"

# ---------------------------------------------------------------------------
say "3. Build the image in Azure"
TAG="$(git rev-parse --short HEAD 2>/dev/null || date +%s)"
az acr build \
  --registry "$ACR_NAME" \
  --image "subjectrank-web:$TAG" \
  --image "subjectrank-web:latest" \
  --file web/Dockerfile \
  web \
  --only-show-errors
echo "  built subjectrank-web:$TAG"

# ---------------------------------------------------------------------------
say "4. Deploy the revision"
az containerapp update \
  -n "$APP_NAME" -g "$RG" \
  --image "$ACR_SERVER/subjectrank-web:$TAG" \
  --only-show-errors -o none
echo "  updated $APP_NAME"

# ---------------------------------------------------------------------------
say "5. Verify — not 'it returned 200'"
EXPECTED=$(python -c "import json;print(json.load(open('web/model/champion.meta.json'))['artifact_sha256'])")
echo "  expecting model sha256 ${EXPECTED:0:16}..."

LIVE=""
for _ in $(seq 1 60); do
  LIVE=$(curl -sf "$APP_URL/api/health" 2>/dev/null \
         | python -c "import sys,json;print(json.load(sys.stdin).get('artifactSha256',''))" 2>/dev/null || true)
  [ "$LIVE" = "$EXPECTED" ] && break
  sleep 5
done

if [ "$LIVE" != "$EXPECTED" ]; then
  echo "  the live revision is not serving the model that was deployed."
  echo "  logs: az containerapp logs show -n $APP_NAME -g $RG --tail 60"
  fail "deploy verification failed"
fi
echo "  live and serving the expected model"

# The constraint that makes everything else irrelevant if it breaks, checked
# against the deployed app rather than only against a laptop.
if command -v node >/dev/null; then
  echo "  checking paste-order invariance against production..."
  SR_BASE="$APP_URL" node parity/order_invariance.mjs
fi

# ---------------------------------------------------------------------------
say "6. Azure ML workspace"
echo "  the site is already live; this half can fail without taking it down"
if az deployment group create \
     -g "$RG" -f azure/infra/main.bicep -p "@$PARAMS" \
     -p deployMachineLearning=true \
     -p containerImage="$ACR_SERVER/subjectrank-web:$TAG" \
     -o none --only-show-errors; then
  echo "  workspace $WORKSPACE ready"
else
  echo "  the ML workspace did not deploy. The site above is unaffected."
  echo "  Usual causes: regional quota, or a soft-deleted Key Vault from a prior"
  echo "  run (az keyvault purge --name ${PREFIX}-kv-...). Re-run to retry."
fi

# ---------------------------------------------------------------------------
say "Done"
cat <<EOF

  $APP_URL

Next:

  source azure/.env.local

  # The ML platform half — training with lineage, and a real model registry.
  python ml/scripts/upload_archive.py --account \$STORAGE_ACCOUNT --container archive
  az ml compute create -f azure/ml/compute.yml   -g \$AZURE_RESOURCE_GROUP -w \$AZURE_ML_WORKSPACE
  az ml job     create -f azure/ml/train_job.yml -g \$AZURE_RESOURCE_GROUP -w \$AZURE_ML_WORKSPACE
  python azure/ml/promote.py --show

  # The D-031 benchmark creates a resource that bills while idle.
  # Measure, then delete. See azure/README.md.

When you are finished:

  az group delete -n $RG --yes --no-wait

EOF
